var configCopyRight = "©2024 M9. All rights reserved";
var configMobileDomain = "https://m.m8bet.net";
var configWapDomain = "http://wap.m8bets.net";
var configMemberDomain = "http://www.m8bets.net/?mob=0";
var configAllowDomain = ["localhost","testmob.m8bets.net", 
"mobile.m8bet.net",
"mobile.m8bets.net",
"mobile.m99m99.net",
"mobile55.m8bets.net",
"mobile.m8huaythai.net",
"mobile.m8huaythai.org",
"mobile.m8huaythai.info",
"333abc.mywinday.com",
"333chy.mywinday.com",
"333xyz.mywinday.com",
"mobile.m8bet333.com",
"mobile.m8bet555.com",
"mobile.m8bet888.com",
"mobile.m8indo.com",
"mobile.mywinday.com",
"mobile.mywinsg.xyz",
"mobile.mwcsg.xyz",
"mobile.wc8.club",
"mobile55.m8bets.net",
/*"mobile.m8666.cc",
"mobile.m8666.online",*/
"mobile2.m8bets.net",
"mobile.m8center.com",
"mobile.m8pools.net",
"mobile.m8pools.org",
"mobile.m8pools.info",
"mobile.colourhe.com",
"mobile.colourhe.net",
"mobile.mywinsg1.com",
"mobile.mywinsg2.net",
"mobile.mywinsg3.club",
"mobile.mywinth1.com",
"mobile.mywinth2.net",
"mobile.mywinth3.club",
"mobile.mywinms1.com",
"mobile.mywinms2.net",
"mobile.mywinms3.club",
"m.m8bets.net",
"m.m8bet.net",
"m.m8bet333.com",
"m.m8bet555.com",
"m.m8bet888.com",
"m.m8indo.com",
"m.mywinday.com",
"m.mywinsg.xyz",
"m.mwcsg.xyz",
"m.wc8.club",
/*"m.m8666.cc",
"m.m8666.online",*/
"m.m8center.com",
"m.m99m99.net",
"m.m8pools.net",
"m.m8pools.org",
"m.m8pools.info",
"m.m8huaythai.net",
"m.m8huaythai.org",
"m.m8huaythai.info",
"m.colourhe.com",
"m.colourhe.net",
"m.mywinsg1.com",
"m.mywinsg2.net",
"m.mywinsg3.club",
"m.mywinth1.com",
"m.mywinth2.net",
"m.mywinth3.club",
"m.mywinms1.com",
"m.mywinms2.net",
"m.mywinms3.club",
"m.m8inside.com",
"m.m8clicks.com",
"m.goom8.com",
"m.33phone.com",
"m.m8book.com",
"m.m9bet.info",
"m.bzone.info",
"m.mbox888.com",
"m.gooom8.com",
"m.mpop88.com",
"m.m8m8bet.net",
"m.m8m8bet.com",
"m.m8online.net",
"m.month88.com",
"m.zonea1.info",
"m.m8mirror.net",
"m.m8mirror.com",
"m.m8cash.net",
"m.startm8.com",
"m.selectm8.com",
"m.m8only.net",
"m.m9bet.org",
"m.goalm8.com",
"m.mpopo88.com",
"m.mbox88.com",
"m.m9bet.net"
];
var contactUS = ""; //Check setContactUs function the need
var configTitle = "M9Bet Mobile";
//var configStats = "http://www.9998bet.net/public/stat?id=";
var configStats = "http://9998bet.net/public/stat";
var Version = "3.0.0";
var configDownloadIOS = "https://mo.bileapps.com/M8Bet/M8Bet.plist";
var configLiveChat = "";
var isMobileApp = true;
var igtxTransferPageUrl = "igtx.mywinday.com/txMobile.aspx?";
var igtxGamePageUrl = "igtx.mywinday.com/txgame.aspx?";
var igtxBlancePage = "igtx2.mywinday.com/txMbWithdraw.aspx?";
var PDLiveTV =  "https://player.twitch.tv";

var configMemberDomainArray = [
						["m.m9bet.net", "www.m9bet.net/?mob=0"],
                        ["testmob.m8bets.net", "www.m8bet.net/?mob=0"],
						["mobile.m8bet.net", "www.m8bet.net/?mob=0"],
						["mobile.m8bets.net", "www.m8bets.net/?mob=0"],
						["mobile55.m8bets.net", "www.m8bet.net/?mob=0"],
						["mobile.m99m99.net", "www.m99m99.net/?mob=0"],
						["mobile.m8huaythai.net", "www.m8huaythai.net/?mob=0"],
						["mobile.m8huaythai.org", "www.m8huaythai.org/?mob=0"],
						["mobile.m8huaythai.info", "www.m8huaythai.info/?mob=0"],
						["333abc.mywinday.com", "www.m8bet.net/?mob=0"],
						["333chy.mywinday.com", "www.m8bet.net/?mob=0"],
						["333xyz.mywinday.com", "www.m8bet.net/?mob=0"],
						["mobile.m8bet333.com", "www.m8bet333.com/?mob=0"],
						["mobile.m8bet555.com", "www.m8bet555.com/?mob=0"],
						["mobile.m8bet888.com", "www.m8bet888.com/?mob=0"],
						["mobile.m8indo.com", "www.m8indo.com/?mob=0"],
						["mobile.mywinday.com", "m8betmb.mywinday.com/?mob=0"],
						["mobile.mywinsg.xyz", "www.mywinsg.xyz/?mob=0"],
						["mobile.mwcsg.xyz", "www.mwcsg.xyz/?mob=0"],
						["mobile.wc8.club", "www.wc8.club/?mob=0"],
						["mobile.m8666.cc", "www.m8666.cc/?mob=0"],
						["mobile.m8666.online", "www.m8666.online/?mob=0"],
						["mobile2.m8bets.net", "www.m8bets.net/?mob=0"],
						["mobile.m8center.com", "www.m8center.com/?mob=0"],
						["mobile.m8pools.net", "www.m8pools.net/?mob=0"],
						["mobile.m8pools.org", "www.m8pools.org/?mob=0"],
						["mobile.m8pools.info", "www.m8pools.info/?mob=0"],
						["mobile.colourhe.com", "www.colourhe.com/?mob=0"],
						["mobile.colourhe.net", "www.colourhe.net/?mob=0"],
						["mobile.mywinsg1.com", "www.mywinsg1.com/?mob=0"],
						["mobile.mywinsg2.net", "www.mywinsg2.net/?mob=0"],
						["mobile.mywinsg3.club", "www.mywinsg3.club/?mob=0"],
						["mobile.mywinth1.com", "www.mywinth1.com/?mob=0"],
						["mobile.mywinth2.net", "www.mywinth2.net/?mob=0"],
						["mobile.mywinth3.club", "www.mywinth3.club/?mob=0"],
						["mobile.mywinms1.com", "www.mywinms1.com/?mob=0"],
						["mobile.mywinms2.net", "www.mywinms2.net/?mob=0"],
						["mobile.mywinms3.club", "www.mywinms3.club/?mob=0"],
						["m.m8bet.net", "www.m8bet.net/?mob=0"],
						["m.m8bets.net", "www.m8bets.net/?mob=0"],
						["m.m99m99.net", "www.m99m99.net/?mob=0"],
						["m.m8huaythai.net", "www.m8huaythai.net/?mob=0"],
						["m.m8huaythai.org", "www.m8huaythai.org/?mob=0"],
						["m.m8huaythai.info", "www.m8huaythai.info/?mob=0"],
						["m.m8bet333.com", "www.m8bet333.com/?mob=0"],
						["m.m8bet555.com", "www.m8bet555.com/?mob=0"],
						["m.m8bet888.com", "www.m8bet888.com/?mob=0"],
						["m.m8indo.com", "www.m8indo.com/?mob=0"],
						["m.mywinday.com", "m8betmb.mywinday.com/?mob=0"],
						["m.mywinsg.xyz", "www.mywinsg.xyz/?mob=0"],
						["m.mwcsg.xyz", "www.mwcsg.xyz/?mob=0"],
						["m.m8666.cc", "www.m8666.cc/?mob=0"],
						["m.m8666.online", "www.m8666.online/?mob=0"],
						["m.m8center.com", "www.m8center.com/?mob=0"],
						["m.m8pools.net", "www.m8pools.net/?mob=0"],
						["m.m8pools.org", "www.m8pools.org/?mob=0"],
						["m.m8pools.info", "www.m8pools.info/?mob=0"],
						["m.colourhe.com", "www.colourhe.com/?mob=0"],
						["m.colourhe.net", "www.colourhe.net/?mob=0"],
						["m.mywinsg1.com", "www.mywinsg1.com/?mob=0"],
						["m.mywinsg2.net", "www.mywinsg2.net/?mob=0"],
						["m.mywinsg3.club", "www.mywinsg3.club/?mob=0"],
						["m.mywinth1.com", "www.mywinth1.com/?mob=0"],
						["m.mywinth2.net", "www.mywinth2.net/?mob=0"],
						["m.mywinth3.club", "www.mywinth3.club/?mob=0"],
						["m.mywinms1.com", "www.mywinms1.com/?mob=0"],
						["m.mywinms2.net", "www.mywinms2.net/?mob=0"],
						["m.mywinms3.club", "www.mywinms3.club/?mob=0"],
						["m.m8inside.com", "www.m8inside.com/?mob=0"],
						["m.m8clicks.com", "www.m8clicks.com/?mob=0"],
						["m.gooom8.com", "www.gooom8.com/?mob=0"],
						["m.33phone.com", "www.33phone.com/?mob=0"],
						["m.m8book.com", "www.m8book.com/?mob=0"],
						["m.goom8.com", "www.goom8.com/?mob=0"],
						["m.mbox888.com", "www.mbox888.com/?mob=0"],
						["m.mpop88.com", "www.mpop88.com/?mob=0"],
						["m.m8m8bet.com", "www.m8m8bet.com/?mob=0"],
						["m.month88.com", "www.month88.com/?mob=0"],
						["m.m8mirror.com", "www.m8mirror.com/?mob=0"],
						["m.startm8.com", "www.startm8.com/?mob=0"],
						["m.selectm8.com", "www.selectm8.com/?mob=0"],
						["m.goalm8.com", "www.goalm8.com/?mob=0"],
						["m.mpopo88.com", "www.mpopo88.com/?mob=0"],
						["m.wc8.club", "www.wc8.club/?mob=0"],
						["m.m9bet.info", "www.m9bet.info/?mob=0"],
						["m.bzone.info", "www.bzone.info/?mob=0"],
						["m.zonea1.info", "www.zonea1.info/?mob=0"],
						["m.m8only.net", "www.m8only.net/?mob=0"],
						["m.m8cash.net", "www.m8cash.net/?mob=0"],
						["m.m8m8bet.net", "www.m8m8bet.net/?mob=0"],
						["m.m8mirror.net", "www.m8mirror.net/?mob=0"],
						["m.m8online.net", "www.m8online.net/?mob=0"],
						["m.m9bet.org", "www.m9bet.org/?mob=0"],
						["m.m9bet.net", "www.m9bet.net/?mob=0"],
						["m.mbox88.com", "www.mbox88.com/?mob=0"],
                    ]